AllCops:
  Exclude:
    - 'bin/*'
    - 'out/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Capfile'
    - 'Gemfile'

GlobalVars:
  AllowedVariables: [$REDIS,$NOTIFIER]

Rails/UnknownEnv:
  Environments:
    - staging
    - production
    - development
    - test

# Scaffoldableが使えなくなるので無効
Rails/LexicallyScopedActionFilter:
  Enabled: false


Metrics/LineLength:
  Max: 180

# 不要なRDocは書いていない
Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7

Metrics/AbcSize:
  Enabled: true
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

# 日本語コメント許可
Style/AsciiComments:
  Enabled: false

# 1行のブロックで{...}ではなく、do...endを使用しているかをチェック
# どっちでもよい
Style/MultilineBlockChain:
  Enabled: false

# Rubyの循環的複雑度をチェック
Metrics/CyclomaticComplexity:
  Max: 6

Style/IfInsideElse:
  Enabled: false

ClassVars:
  Enabled: false

HandleExceptions:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 200

# DSLで書かれている部分以外は、20行縛り
Metrics/BlockLength:
  Max: 20
  Exclude:
    - Gemfile
    - spec/**/*
    - lib/tasks/**/*

# 文字列は"縛り
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
