development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: mention_collection_development

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: mention_collection_staging

staging_heroku:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: mention_collection_staging_heroku

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: mention_collection_production
